image:
  name: hashicorp/terraform:0.12.21
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

stages:
  - Test and Lint
  - Build and Push
 

Test and Lint:
  image: docker:20.10.8
  services:
    - name: docker:dind
      command: ["--mtu=1300"]
  stage: Test and Lint
  script:
    - echo "Test happens here"
  rules:
    - if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH =~ /^(main|production)$/"

sast:
  stage: Test and Lint
include:
- template: Security/SAST.gitlab-ci.yml

Validate Terraform:
  stage: Test and Lint
  script:
    - cd deploy/
    - terraform init -backend=false
    - terraform validate
    - terraform fmt -check
  rules:
    - if: "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(main|production)$/ || $CI_COMMIT_BRANCH =~ /^(main|production)$/"

Build and Push:
  image: docker:20.10.8
  services:
    - name: docker:dind
      command: ["--mtu=1300"]
  stage: Build and Push
  script:
    - wget https://github.com/digitalocean/doctl/releases/download/v1.72.0/doctl-1.72.0-linux-amd64.tar.gz
    - tar xf ./doctl-1.72.0-linux-amd64.tar.gz
    - mv ~/doctl /usr/local/bin
    - doctl registry login -t $DIGITALOCEAN_TOKEN
    - docker build --compress -t $CR_REPO:$CI_COMMIT_SHORT_SHA .
    - docker push $CR_REPO:$CI_COMMIT_SHORT_SHA
    - docker tag $CR_REPO:$CI_COMMIT_SHORT_SHA $CR_REPO:latest
    - docker push $CR_REPO:latest
  rules:
    - if: "$CI_COMMIT_BRANCH =~ /^(main|production)$/"
